
name: Sysmon
main: org.servertools.sysmon.SysmonPlugin
version: 1.2
api-version: 1.20
description: Systemmonitor mit CSV-Ausgabe und Redstone-/Chunk-/TPS-Auswertung
commands:
  sysmon:
    usage: /<command> stats [Minuten]
    description: Zeigt Sysmon-Statistiken über CSV-Daten
